ad = input ("adınız nedir")
print ("Merhaba", ad)
kenar = int(input ("karenin bir kenarının uzunluğu nedir"))
print ("Karenin çevresi", (kenar*4))
print ("Karenin alanı =", (kenar*kenar))
sayi1 = int(input ("birinci sayıyı giriniz"))
sayi2 = int(input ("ikinci sayıyı giriniz"))
print("sayıların toplamı ",sayi1+sayi2)
print("sayıların carpımı ",sayi1*sayi2)
print("birinci sayının ikinci sayıdan farkı ",sayi1-sayi2)
print("birinci sayının ikinci sayıya bölümü ",sayi1/sayi2)
yas = int(input("doğum yılınız nedir"))
print (2025-yas," yaşındasınız")
not1 = int(input("1. notunuz nedir"))
not2 = int(input("2. notunuz nedir"))
print ("ortalam notunuz =",(not1+not2)/2)
cinsiyet = input ("cinsiyetiniz nedir erkek/kadın")
boy = int(input("boyunuz kaç cm"))
#idealerkek = (50+((2.3/2.54)*boy)-152.4)
#idealkadin = (50+((2.3/2.54)*boy)-152.4)
if cinsiyet == "erkek" :  print ("ideal kilonuz = ",(50+((2.3/2.54)*boy)-152.4))
elif cinsiyet == "kadın" : print ("ideal kilonuz = ",(45.5+((2.3/2.54)*boy)-152.4))
else : print("cinsiyeti yanlış girdiniz")
akenar = int(input("üçgenin a kenarı giriniz"))
bkenar = int(input("üçgenin b kenarı giriniz"))
ckenar = int(input("üçgenin c kenarı giriniz"))
ayuksek = int(input("üçgenin a kenarı yüksekliğini giriniz"))
print ("üçgenin çevresi = ",akenar+bkenar+ckenar)
print ("üçgenin alanı = ",akenar*ayuksek/2)
yaricap = int(input("dairenin yarı çapını giriniz"))
print ("dairenin çevresi =",3.14159*yaricap*2)
print ("dairenin alani =",3.14159*yaricap*yaricap)


